### ISSUE TITLE
MIT License or similar?

### ISSUE THREAD

**Issue by ghost** [VonKeebler/BananaMud#1]
Hi I didn't see a license, are we able to use this?

**Comment by VonKeebler** [comment]
I guess if you want to. I seem to recall that Phaser.io had a problem rendering so much text or text objects then having to shift everything upward to produce a terminal style read out.

I might use the setting described in the rooms but if you just want the functionality go for it.

**Comment by ghost** [comment]
Awesome, yes just looking to learn from it. Phaser also a great starting point for teaching others about art and game design. Thanks!
